VIidly/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VIidly.Controllers
{
    public class RentalsController : Controller
    {
        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }
    }
}

VIidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*Typo in _NavBat should be _NavBar*@
    @Html.Partial("_NavBat")
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    
    @RenderSection("scripts", required: false)
</body>
</html>

VIidly/Views/Shared/_NavBat.cshtml
<nav class="navbar navbar-expand-sm navbar-light bg-light fixed-top justify-content-between">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        @Html.ActionLink("Vidly Movie Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <div class="navbar-collapse collapse">

            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("New Rental", "New", "Rentals", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Customers", "Index", "Customers", null, new {@class = "nav-link"})</li>
                <li class="nav-item">@Html.ActionLink("Movies", "Index", "Movies", null, new {@class = "nav-link"})</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>
<br />